version: '3.8'

services:
  app:
    container_name: loginuser-jwt
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data-db:/data/db
volumes:
  data-db: